# Generated by Django 5.0.3 on 2024-03-14 04:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
